// ============================================================================
//  CS1231S Midterm Condensed: Revision Addendum
//  All new content, definitions, and revisions added since initial commit (062d28e).
//  Designed as a companion to the printed initial-commit notes.
// ============================================================================

#let accent = rgb("#1d4e89")
#let ink    = rgb("#1b1d21")
#let muted  = rgb("#5f6670")

#set document(title: "CS1231S Midterm Condensed: Addendum", author: "CS1231S revision")
#set page(
  paper: "a4",
  margin: (x: 12mm, top: 12mm, bottom: 12mm),
  header: context {
    let pg = here().page()
    if pg > 1 {
      set text(size: 7.5pt, fill: muted)
      stack(spacing: 3pt,
        grid(columns: (1fr, auto), [CS1231S · Midterm Condensed Addendum], [Revisions since Initial Commit]),
        line(length: 100%, stroke: 0.4pt + luma(200)),
      )
    }
  },
  footer: context {
    set text(size: 7.5pt, fill: muted)
    align(center)[#counter(page).display()]
  },
)
#set text(font: "New Computer Modern", size: 10.3pt, fill: ink, lang: "en")
#set par(justify: true, leading: 0.66em, spacing: 0.88em)
#set enum(numbering: "1.1.", full: true, spacing: 0.58em, indent: 0.3em, body-indent: 0.55em)
#set list(spacing: 0.58em, indent: 0.3em, body-indent: 0.55em)
#set table(stroke: 0.4pt + luma(190), inset: (x: 6pt, y: 4pt))
#show table.cell.where(y: 0): set text(weight: "bold")
#show table: set par(justify: false)

// Allow inline equations to wrap only before a relation operator.
#show math.equation.where(block: false): it => {
  // Guard the complete terms generated by this rule.
  if it.has("label") and it.label == <math-term> { return box(it) }
  let children = if it.body.has("children") { it.body.children } else { (it.body,) }
  let chunks = ()
  let term = []
  let has-term = false
  for child in children {
    let literal = if child.has("text") and type(child.text) == str { child.text } else { none }
    let relation = literal in ("=", "≡", "↔", "⇔", "⇒")
    if relation and has-term {
      chunks.push(term)
      term = []
    }
    term += child
    if literal == none or literal.trim() != "" { has-term = true }
  }
  chunks.push(term)
  chunks.map(term => box([#math.equation(term) <math-term>])).join(h(0.2em))
}

#show heading.where(level: 1): it => {
  v(0pt)
  block(width: 100%, above: 1.8em, below: 1.1em, sticky: true, {
    set text(size: 14pt, weight: "bold", fill: accent)
    it.body
    v(-7pt)
    line(length: 100%, stroke: 1.1pt + accent)
  })
}
#show heading.where(level: 2): it => block(above: 1.3em, below: 0.7em,
  text(size: 11pt, weight: "bold", fill: accent, it.body))
#show heading.where(level: 3): it => block(above: 1.0em, below: 0.55em,
  text(size: 9.8pt, weight: "bold", it.body))

// ---- math shorthands ---------------------------------------------------------
#let lnot  = math.class("unary", sym.tilde.op)        // ~p
#let simq  = math.class("normal", sym.tilde.op)       // A/~ , [x]_~
#let pleq  = sym.prec.curly.eq                        // ≼
#let plin  = math.attach(sym.prec.curly.eq, tr: $*$)  // ≼*
#let dv    = sym.divides
#let ndv   = sym.divides.not
#let PP    = $cal(P)$

// ---- boxes ------------------------------------------------------------------
#let kbox(label, col, bg, title, body, split: false) = block(
  width: 100%, inset: (x: 10pt, y: 7.5pt), radius: 1.5pt, fill: bg,
  stroke: (left: 2.2pt + col), above: 0.95em, below: 0.95em, breakable: split,
  {
    set par(justify: false)
    block(sticky: true, below: 0.55em, {
      text(size: 7.2pt, weight: "bold", fill: col, tracking: 0.4pt, upper(label))
      if title != none { h(6pt); text(weight: "bold", title) }
    })
    body
  })
#let defn(title, body) = block(
  width: 100%, inset: (x: 12pt, y: 10pt), radius: 2pt, fill: rgb("#e7eff9"),
  stroke: (left: 4pt + accent, top: 0.7pt + accent, right: 0.7pt + accent, bottom: 0.7pt + accent),
  above: 1.15em, below: 1.15em, breakable: false,
  {
    set par(justify: false, leading: 0.7em)
    block(sticky: true, below: 0.7em, {
      text(size: 7.8pt, weight: "bold", fill: accent, tracking: 0.6pt, "DEFINITION")
      if title != none { h(7pt); text(size: 12pt, weight: "bold", fill: accent, title) }
    })
    set text(size: 11.2pt)
    body
  })
#let thm(title, body)   = kbox("Theorem", rgb("#1f6f43"), rgb("#edf6f0"), title, body)
#let proofb(title, body)= kbox("Proof", rgb("#44484f"), rgb("#f6f6f7"), title, body, split: true)
#let trap(title, body)  = kbox("Trap", rgb("#a23a2a"), rgb("#fbefec"), title, body)
#let exam(title, body)  = kbox("Past paper", rgb("#8a5a00"), rgb("#fdf5e3"), title, body)
#let tip(title, body)   = kbox("Method", rgb("#5b3f8c"), rgb("#f3effa"), title, body)

#let example(title, body) = kbox("Worked example", rgb("#44484f"), rgb("#f6f6f7"), title, body, split: true)
#import "lecture_reference.typ": lecture-reference

#let j(it) = h(0.3em) + text(size: 8.2pt, fill: muted, style: "italic")[(#it)]
#let qed = h(1fr) + $square.filled$

// ============================================================================
= CS1231S Condensed Notes · Revision Addendum
// ============================================================================

#text(size: 9.5pt, fill: muted)[
This addendum compiles all content added or refined after the initial commit (`062d28e`), including lecture definitions, equivalence relation notes, well-defined operations on quotient sets, selected tutorial proofs (Part VI), updated index terms, and the complete Appendix A and lecture theorem reference (Part VIII). All material is integrated into the current condensed notes, whose §32 is now a topic locator. This addendum remains a companion for an initial printed copy. Tutorial solutions are adapted from the supplied answers, with explicit domains and justifications.
]

// ============================================================================
== Part I · Logic & Arguments (§1, §3, §4)
// ============================================================================

#defn[Negation (2.1.2) · Conjunction (2.1.3) · Disjunction (2.1.4) · §1][
For statement variables $p$ and $q$: the *negation* of $p$ is "not $p$" or "it is not the case that $p$", denoted $lnot p$; the *conjunction* of $p$ and $q$ is "$p$ and $q$", denoted $p and q$; the *disjunction* of $p$ and $q$ is "$p$ or $q$", denoted $p or q$ (inclusive: true when either or both are true).]

#tip[Clarification on §1 & §3 Wording][
- *Tautological / Contradictory statements (§1):* A statement whose statement form is a tautology (contradiction) is called a *tautological* (*contradictory*) statement.
- *Conditional terminology (§3):* In $p -> q$ ("if $p$ then $q$", "$p$ implies $q$"), $p$ is called the *hypothesis* (or *antecedent*) and $q$ is called the *conclusion* (or *consequent*).
]

#defn[Argument, validity (2.3.1) · Critical row · Syllogism · Sound, unsound (2.3.2) · §4][
An *argument* (*argument form*) is a sequence of statements (statement forms); all but the last are *premises* (assumptions, hypotheses), the last (after $therefore$) is the *conclusion*. \
An argument form is *valid* iff, whatever statements are substituted for its variables, if the premises are all true then the conclusion is true. \
A *critical row* is a truth-table row in which all premises are T: the form is valid iff the conclusion is T in every critical row. \
A *syllogism* is an argument form with two premises and a conclusion (e.g. modus ponens). \
An argument is *sound* iff it is valid *and* all its premises are true; otherwise it is *unsound*.]

// ============================================================================
== Part II · Predicates, Quantifiers & Proofs (§5, §8, §10)
// ============================================================================

#defn[Domain of discourse & Truth set (§5 update)][
The *domain* of a variable is also termed the *domain of discourse*, *universe of discourse*, *universal set*, or *universe*. The *truth set* of $P(x)$, $x in D$, is the set of all elements of $D$ that make $P(x)$ true: ${x in D : P(x)}$, also denoted ${x in D | P(x)}$.]

#defn[Kinds of mathematical statements (Lecture 1) · §5][
- A *universal statement* says a property holds for *all* elements of a set ($forall$; "all", "every", "any").
- A *conditional statement* says that if one thing is true then another must be ($->$; "if … then").
- An *existential statement* says there is *at least one* thing with the property ($exists$; "there exists", "some").
- A *universal conditional statement* is both universal and conditional: $forall x thin (P(x) -> Q(x))$ (e.g. "for all animals $a$, if $a$ is a dog then $a$ is a mammal").
- A *universal existential statement* has the form $forall x thin exists y thin ...$ (e.g. "every real number has an additive inverse").
- An *existential universal statement* has the form $exists x thin forall y thin ...$ (e.g. "there is a positive integer that is $<=$ every positive integer").]

#defn[Valid argument form with quantifiers (3.4.1) · §8][
An argument form is *valid* iff, no matter what particular predicates are substituted for the predicate symbols in its premises, if the resulting premise statements are all true then the conclusion is also true. An argument is *valid* iff its form is valid.]

#defn[Absolute value (Lecture 1) · Colorful (Lecture 1, CS1231S only) · §10][
For $x in RR$, the *absolute value* of $x$ is $|x| = x$ if $x >= 0$, and $|x| = -x$ if $x < 0$. \
An integer $n$ is *colorful* iff there exists some integer $k$ such that $n = 3k$. (Used in lecture: $-1353 = 3 dot (-451)$ and $0 = 3 dot 0$ are colorful; 7 is not.)]

#tip[Axioms & Primes (§10 updates)][
- *Axiom / postulate:* Assumed true without proof (Peano axioms, Euclid's postulates).
- *Equivalent prime definition:* $n in ZZ$ with $n > 1$ is prime iff $forall r, s in ZZ thin (r > 1 and s > 1 -> r s != n)$.
]

// ============================================================================
== Part III · Sets & Operations (§13, §14, §16)
// ============================================================================

#defn[Set-roster notation & Cardinality (§13 update)][
- *Set-roster:* list all elements between braces: ${1, 2, 3}$, ${1, 2, ..., 100}$, ${1, 2, 3, ...}$ (the ellipsis "…" reads "and so forth").
- *Set elements:* $x in S$ ($x$ is a *member* or *element*); $x in.not S$ means it is not.
- *Cardinality $|S|$:* the size of $S$, the number of elements of $S$.]

#defn[Interval notation (Lecture 5) · §13][
For real numbers $a <= b$:
$ (a, b) = {x in RR : a < x < b}, quad [a, b] = {x in RR : a <= x <= b}, $
$ (a, b] = {x in RR : a < x <= b}, quad [a, b) = {x in RR : a <= x < b}. $
Unbounded intervals:
$ (a, oo) = {x in RR : x > a}, quad [a, oo) = {x in RR : x >= a}, $
$ (-oo, b) = {x in RR : x < b}, quad (-oo, b] = {x in RR : x <= b}. $
*Note:* The interval $(a, b)$ and the ordered pair $(a, b)$ look identical; context distinguishes them.]

#defn[Superset · Singleton (§14 update)][
- If $A subset.eq B$, we write $B supset.eq A$: "$B$ contains / includes $A$", "$B$ is a *superset* of $A$".
- $A subset.neq B$ denotes *proper* (strict) inclusion.
- The *empty set* $nothing = {}$ has no elements; a set with exactly one element is a *singleton*.]

#defn[Universal set · Relative complement (§16 update)][
- A *universal set* (universe of discourse) $U$ contains every object under discussion (e.g. $RR$ when all sets are sets of reals).
- $B without A = {x in U : x in B and x in.not A}$ is also called the *relative complement* of $A$ in $B$.]

// ============================================================================
== Part IV · Relations, Digraphs & Equivalence (§19, §23)
// ============================================================================

#defn[Relation notation · Directed graph · $n$-ary relations (§19 update)][
- $x R y$ means "$x$ is $R$-related to $y$"; $x cancel(R) y$ means $(x, y) in.not R$.
- A *(binary) relation on $A$* is a subset of $A times A = A^2$; an $n$-ary relation on $A$ is a subset of $A^n$.
- The *directed graph* (digraph) of $R$ on $A$ draws each element of $A$ once as a vertex, with a directed arrow $x -> y$ whenever $x R y$ and a self-loop at $x$ when $x R x$.
- An *$n$-ary relation* on $A_1 times dots.c times A_n$ is a subset of the Cartesian product (binary, ternary, quaternary for $n=2, 3, 4$).]

#defn[Procedural class definition · Congruence modulo $n$ (Lecture 6.3.4) · §23][
- Procedural equivalence class: $forall x in A thin (x in [a]_simq <-> a tilde.op x)$.
- Let $a, b in ZZ$ and $n in ZZ^+$. $a$ is *congruent to $b$ modulo $n$*, written $a equiv b space (mod n)$, iff $a - b = n k$ for some $k in ZZ$ (i.e. $n dv (a - b)$).
- Classes: $[x] = {x + n k : k in ZZ}$, and $ZZ slash simq_n = {[0], [1], ..., [n - 1]}$.]

#defn[Representative · Well-defined operation on $A slash simq$ · §23][
Any $b in [a]$ is a *representative* of $[a]$, since then $[b] = [a]$: mod 5, $[2] = [7] = [12]$. \
Let $tilde.op$ be an equivalence relation on $A$ and $ast.op$ a binary operation on $A$ (so $a ast.op b in A$ for all $a, b in A$). The induced rule $[a] ast.op [b] = [a ast.op b]$ is *well defined* iff the answer depends only on the classes, not on the representatives chosen:
$ a tilde.op a' and b tilde.op b' => a ast.op b tilde.op a' ast.op b'. $]

#proofb[$+$ and $dot$ are well defined on the classes of congruence mod $n$ · §23][
+ Fix $n in ZZ^+$ and let $a, a', b, b' in ZZ$ with $a equiv a' space (mod n)$ and $b equiv b' space (mod n)$: $a - a' = n k$ and $b - b' = n m$ for some $k, m in ZZ$ #j[definition of congruence].
+ (Addition) $(a + b) - (a' + b') = n(k + m)$ with $k + m in ZZ$ #j[closure], so $a + b equiv a' + b' space (mod n)$.
+ (Multiplication) $a b - a' b' = (a - a') b + a'(b - b') = n(k b + a' m)$ with $k b + a' m in ZZ$ #j[closure], so $a b equiv a' b' space (mod n)$. #qed
E.g. mod 5: $[2] dot [4] = [8] = [3]$ and $[7] dot [9] = [63] = [3]$.]

#trap[Check reflexive, symmetric, transitive first · then check well-definedness · §23][
- $a tilde.op b <-> a b >= 0$ is *not* transitive on $RR$ ($1 tilde.op 0$ and $0 tilde.op -1$, but $1 tilde.not -1$), so it does not give a partition into equivalence classes. On $RR without {0}$ it means "same sign": $(RR without {0}) slash simq = {[1], [-1]} = {(0, oo), (-oo, 0)}$.
- $a tilde.op b <-> a - b = 2k$ for some $k in ZZ$, on $RR$: $[a] = {a + 2k : k in ZZ}$ and $RR slash simq = {[r] : 0 <= r < 2}$ (infinitely many classes). $+$ is well defined, but $dot$ is *not*: $[0.5] = [2.5]$, yet $[0.5] dot [0.5] = [0.25] != [1.25] = [2.5] dot [0.5]$, since $1.25 - 0.25 = 1$ is not of the form $2k$.]

// ============================================================================
== Part V · Partial Orders & Well-Ordered Sets (§24)
// ============================================================================

#defn[Maximal and minimal alternate characterizations (§24 update)][
- $c$ *maximal* $<=> forall x in A thin (c pleq x -> c = x)$. Equivalently, every $x in A$ has $x pleq c$ or is not comparable with $c$.
- $c$ *minimal* $<=> forall x in A thin (x pleq c -> c = x)$. Equivalently, every $x in A$ has $c pleq x$ or is not comparable with $c$.]

#defn[Well-ordered set (Lecture 6.4.7) · §24][
Let $pleq$ be a total order on a set $A$. $A$ is *well-ordered* iff every non-empty subset of $A$ contains a smallest element. Symbolically,
$ forall S in PP(A) thin (S != nothing -> exists x in S thin forall y in S thin (x pleq y)). $
$(NN, <=)$ is well-ordered. $(ZZ, <=)$ is not: $ZZ$ itself (or $ZZ^-$) is a non-empty subset with no smallest element. \
*Theorem:* Every total order on a finite set is well-ordered (a non-empty subset has a minimal element, which in a total order is smallest).]

// ============================================================================
== Part VI · Tutorial Worked Examples (Tutorials 1–5)
// ============================================================================

#text(size: 9.5pt, fill: muted)[Model solutions adapted from Tutorials 1–5, in the numbered-line, justified style of the main notes. Each illustrates a standard proof pattern. Results already covered by the initial notes ($A subset.eq B <-> A union B = B$, associativity of $compose$, $QQ$ closed under $+$, $R$ symmetric $<-> R = R^(-1)$, AY23 Q12) are omitted here. The tutorial locator in §29 of the current condensed notes gives the integrated locations.]

=== Proof techniques (Tutorials 1–2)

#example[T1 Q11 · Biconditional: $n^2$ is odd $<->$ $n$ is odd][
For $n in ZZ$, Smart writes: "*Proof (by contradiction).* Suppose $n$ is even, so $n = 2k$, … so $n^2$ is even. So if $n$ is even then $n^2$ is even, i.e. if $n^2$ is odd then $n$ is odd. Therefore $n^2$ is odd iff $n$ is odd." Comment, then give a correct proof.

Let $n in ZZ$. *Faults:* (1) only one direction ($n^2$ odd $-> n$ odd) is proved; (2) the method is *contraposition*, not contradiction; (3) justifications are missing (definition of even, closure).
+ ($=>$) Prove the contrapositive of "if $n^2$ is odd, then $n$ is odd".
  + Suppose $n$ is even. Then $exists k in ZZ$ s.t. $n = 2k$ #j[definition of even].
  + $n^2 = (2k)^2 = 4k^2 = 2(2k^2)$ #j[basic algebra], with $2k^2 in ZZ$ #j[closure of integers under $times$].
  + So $n^2$ is even #j[definition of even]. This proves: if $n^2$ is odd, then $n$ is odd #j[contraposition and the even/odd dichotomy].
+ ($arrow.l.double$) Suppose $n$ is odd: $n = 2k + 1$ for some $k in ZZ$ #j[definition of odd]. Then $n^2 = 2(2k^2 + 2k) + 1$, with $2k^2 + 2k in ZZ$ #j[basic algebra, closure], so $n^2$ is odd #j[definition of odd].
+ Therefore $n^2$ is odd iff $n$ is odd #j[lines 1 and 2]. #qed]

#example[T2 Q8 · Cases inside a conditional][
Prove $forall x in RR thin ((x^2 > x) -> ((x < 0) or (x > 1)))$. Must the case $x^2 <= x$ be examined?

*No:* $p -> q$ is true whenever $p$ is false, so only $x^2 > x$ needs examining.
+ Let $r$ be an arbitrarily chosen real number.
+ Suppose $r^2 > r$.
  + Then $r^2 - r > 0$, i.e. $r(r - 1) > 0$ #j[basic algebra].
  + So $r$ and $r - 1$ are both positive or both negative #j[Appendix A, T25].
  + *Case 1:* both positive. Then $r - 1 > 0$, so $r > 1$ #j[basic algebra].
  + *Case 2:* both negative. Then $r < 0$ #j[case assumption].
  + Hence $(r > 1) or (r < 0)$; so $(r^2 > r) -> ((r > 1) or (r < 0))$ #j[division into cases].
+ Therefore $forall x in RR thin ((x^2 > x) -> ((x < 0) or (x > 1)))$ #j[universal generalization, as $r$ was arbitrary]. #qed
Do not use diagrams (e.g. graphs) as proofs unless instructed.]

#exam[T2 Q11 · Past midterm · A factor is at most $sqrt(n)$][
For $n, a, b in ZZ^+$, prove $n = a b -> (a <= sqrt(n) or b <= sqrt(n))$.
*By contraposition* ($p -> q equiv lnot q -> lnot p$):
+ Contrapositive: if $a > sqrt(n)$ and $b > sqrt(n)$, then $n$ is not the product $a b$ #j[De Morgan's law].
+ Suppose $a > sqrt(n)$ and $b > sqrt(n)$. Then $a b > sqrt(n) dot sqrt(n) = n$ #j[Appendix A, T27].
+ Since $a b != n$, the contrapositive is true; therefore the original statement is true. #qed
*By contradiction* ($lnot(p -> q) equiv p and lnot q$):
+ Suppose not: $n = a b$ and $a > sqrt(n)$ and $b > sqrt(n)$ #j[De Morgan's law].
+ Then $a b > sqrt(n) dot sqrt(n) = n$ #j[Appendix A, T27], contradicting $n = a b$ in line 1. #qed
_T27:_ if $0 < a < c$ and $0 < b < d$, then $0 < a b < c d$.]

#trap[T2 Q4 · Closure claims][
$ZZ$ is *not* closed under division ($3 slash 2 = 1.5 in.not ZZ$). Division is not a binary operation on *all* of $QQ times QQ$, since $r slash 0$ is undefined; division of a rational by a *nonzero* rational does give a rational. In proving $QQ$ closed under $+$, the line "$b d != 0$ #j[zero product property]" is required, and is commonly omitted.]

=== Sets (Tutorial 3)

#example[T3 Q4 · Set equality by double inclusion][
$A = {2n + 1 : n in ZZ}$, $B = {2n - 5 : n in ZZ}$. Is $A = B$? Prove it.

+ ($subset.eq$) Let $a in A$.
  + Use the definition of $A$ to find an integer $n$ such that $a = 2n + 1$.
  + Then $a = 2n + 1 = 2(n + 3) - 5$, and $n + 3 in ZZ$ #j[closure of integers under $+$].
  + Therefore $a in B$ #j[definition of $B$].
+ ($supset.eq$) Let $b in B$; find $n in ZZ$ with $b = 2n - 5$. Then $b = 2(n - 3) + 1$ with $n - 3 in ZZ$ #j[closure under $-$], so $b in A$ #j[definition of $A$].
+ Therefore $A = B$ #j[definition of set equality]. #qed
The change of variables $k = n + 3$ is valid only after showing it ranges over *all* integers: for each $k in ZZ$, take $n = k - 3 in ZZ$. Closure alone does not justify that step; double inclusion makes both directions explicit.]

#example[T3 Q5 · Element method as a set-builder chain][
Prove that for all sets $A, B, C$: $A inter (B without C) = (A inter B) without C$.

$A inter (B without C) = {x : x in A and x in (B without C)}$ #j[definition of $inter$] \
$quad = {x : x in A and (x in B and x in.not C)}$ #j[definition of $without$] \
$quad = {x : (x in A and x in B) and x in.not C}$ #j[associativity of $and$] \
$quad = {x : x in A inter B and x in.not C}$ #j[definition of $inter$] \
$quad = (A inter B) without C$ #j[definition of $without$]. #qed]

#example[T3 Q6 · Symmetric difference by set identities only][
(a) $A = {1, 4, 9, 16}$, $B = {2, 4, 6, ..., 16}$: find $A xor B$. (b) Using Theorem 6.2.2, prove $A xor B = (A union B) without (A inter B)$.

(a) $A without B = {1, 9}$, $B without A = {2, 6, 8, 10, 12, 14}$, so $A xor B = {1, 2, 6, 8, 9, 10, 12, 14}$. \
(b) $A xor B = (A without B) union (B without A)$ #j[definition of $xor$]
+ $= (A inter overline(B)) union (B inter overline(A))$ #j[set difference law]
+ $= ((A inter overline(B)) union B) inter ((A inter overline(B)) union overline(A))$ #j[distributive law]
+ $= ((A union B) inter (overline(B) union B)) inter ((A union overline(A)) inter (overline(B) union overline(A)))$ #j[distributive, commutative laws]
+ $= ((A union B) inter U) inter (U inter (overline(A) union overline(B)))$ #j[commutative, complement laws]
+ $= (A union B) inter (overline(A) union overline(B))$ #j[commutative, identity laws]
+ $= (A union B) inter overline(A inter B)$ #j[De Morgan's law]
+ $= (A union B) without (A inter B)$ #j[set difference law]. #qed]

#trap[T3 Q3(c) · $A times PP(B) != PP(A times B)$][
For every $A, B$, $nothing in PP(A times B)$ #j[$nothing subset.eq A times B$], but $nothing in.not A times PP(B)$ #j[every member of a Cartesian product is an ordered pair; $nothing$ is not one]. This named witness proves the sets differ. A cardinality "proof" ($n dot 2^k != 2^(n k)$ for $|A| = n$, $|B| = k$) is wrong: equality holds when $n = 1$, or $n = 2$ and $k = 1$.]

=== Relations and orders (Tutorials 4–5)

#example[T4 Q10 · Equivalence relation using Appendix A][
On $ZZ without {0}$ let $a tilde.op b <-> a b > 0$. (a) Prove $tilde.op$ is an equivalence relation. (b) Determine all distinct equivalence classes.

+ (Reflexivity) Let $a in ZZ without {0}$. Since $a != 0$, $a^2 > 0$ #j[T21]. Thus $a tilde.op a$ #j[definition of $tilde.op$].
+ (Symmetry) Let $a, b in ZZ without {0}$ with $a tilde.op b$. Then $a b > 0$ #j[definition of $tilde.op$], so $b a > 0$ #j[commutative law of $times$], so $b tilde.op a$.
+ (Transitivity) Let $a, b, c in ZZ without {0}$ with $a tilde.op b$ and $b tilde.op c$. Then $a b > 0$ and $b c > 0$ #j[definition of $tilde.op$].
  + Multiplying, $a b^2 c > 0$ #j[Ord1], so $(a c) b^2 > 0$ #j[associative, commutative laws of $times$].
  + So $a c$ and $b^2$ are both positive or both negative #j[T25].
  + Since $b^2 > 0$ #j[T21, as $b != 0$], $a c > 0$. Thus $a tilde.op c$.
+ Therefore $tilde.op$ is an equivalence relation. #qed
(b) T25 rules out pairs of opposite signs; the product of two positive or two negative integers is positive. The classes are $[1] = ZZ^+$ and $[-1] = ZZ^-$, so $(ZZ without {0}) slash simq = {ZZ^+, ZZ^-}$. \
_T21:_ $a != 0 => a^2 > 0$. $quad$ _Ord1:_ $a, b > 0 => a + b > 0 and a b > 0$. $quad$ _T25:_ $a b > 0 =>$ $a, b$ both positive or both negative.]

#example[T4 Q9 · Inverse and composition by the element method][
$S = {(m, n) in ZZ^2 : m^2 + n^2 "is even"}$. Determine (a) $S^(-1)$, (b) $S compose S$, (c) $S compose S^(-1)$.

(a) $S^(-1) = {(x, y) in ZZ^2 : (y, x) in S}$ #j[definition of inverse] \
$= {(x, y) in ZZ^2 : y^2 + x^2 "is even"}$ #j[definition of $S$] \
$= {(x, y) in ZZ^2 : x^2 + y^2 "is even"}$ #j[commutativity of $+$] \
$= S$. \
(b) $S compose S = S$:
+ ($subset.eq$) Let $(x, z) in S compose S$. Then $(x, y) in S$ and $(y, z) in S$ for some $y in ZZ$ #j[definition of composition].
  + So $x^2 + y^2$ and $y^2 + z^2$ are even #j[definition of $S$], hence $x^2 + 2y^2 + z^2$ is even #j[sum of two even integers].
  + As $2y^2$ is even #j[definition of even, closure], $x^2 + z^2$ is even #j[difference of two even integers], so $(x, z) in S$ #j[definition of $S$].
+ ($supset.eq$) Let $(x, z) in S$. Note $(x, x) in S$, as $x^2 + x^2$ is even. Since $(x, x) in S$ and $(x, z) in S$, $(x, z) in S compose S$ #j[definition of composition].
+ Therefore $S compose S = S$. #qed
(c) $S compose S^(-1) = S compose S = S$ by (a) and (b). \
_Alternative for ($supset.eq$):_ by cases. If $x^2$ is odd, so is $z^2$, and $(x, 1), (1, z) in S$. If $x^2$ is even, so is $z^2$, and $(x, 0), (0, z) in S$.]

#exam[T4 Q8 (AY20/21 exam) · T4 Q6 (AY23/24 exam)][
*Q8.* On $ZZ^+ times ZZ^+$, $(a, b) tilde.op (c, d) <-> a b = c d$. Write the set-builder line first: $[(1, 1)] = {(x, y) in ZZ^+ times ZZ^+ : (1, 1) tilde.op (x, y)}$ #j[definition of class] \
$= {(x, y) in ZZ^+ times ZZ^+ : x y = 1}$ #j[definition of $tilde.op$] \
$= {(1, 1)}$. Likewise $[(4, 3)] = {(x, y) in ZZ^+ times ZZ^+ : x y = 12} = {(1,12), (2,6), (3,4), (4,3), (6,2), (12,1)}$. \
*Q6.* $R = {(1,1), (1,2), (2,1), (2,2), (3,3)}$ on ${1, 2, 3}$; find $R compose R compose dots.c compose R$ (7 copies). $R$ is an equivalence relation, so $R compose R = R$ (AY23 Q12, §23). By associativity, $R^7 = ((R compose R) compose (R compose R)) compose ((R compose R) compose R) = (R compose R) compose (R compose R) = R compose R = R$.]

#example[T5 Q6 · Reflexive closure (the closure-proof template)][
Let $R$ be a relation on a non-empty set $A$, and define $S$ on $A$ by $x S y <-> ((x = y) or (x R y))$. Show: (a) $S$ is reflexive; (b) $R subset.eq S$; (c) if $S'$ is a reflexive relation on $A$ and $R subset.eq S'$, then $S subset.eq S'$. What is $S$ called?

(a) Let $x in A$. $x = x$, so $x S x$ #j[definition of $S$]. Therefore $S$ is reflexive. \
(b) Suppose $(x, y) in R$. Then $x S y$ #j[definition of $S$], so $(x, y) in S$. Therefore $R subset.eq S$ #j[definition of $subset.eq$]. \
(c) Let $(x, y) in S$: $x = y$ or $x R y$ #j[definition of $S$].
+ *Case 1 ($x = y$):* $x S' y$ #j[$S'$ is reflexive], so $(x, y) in S'$.
+ *Case 2 ($x R y$):* $(x, y) in R subset.eq S'$, so $(x, y) in S'$.
In all cases $(x, y) in S'$. Therefore $S subset.eq S'$. #qed \
$S$ is the *reflexive closure* of $R$: the smallest reflexive relation on $A$ containing $R$. Parts (a)–(c) mirror the three conditions defining a closure.]

#example[T5 Q7 · Asymmetric vs antisymmetric][
On $A = {a, b, c}$ find a relation that is (a) asymmetric and antisymmetric; (b) antisymmetric but not asymmetric; (c) asymmetric but not antisymmetric; (d) neither.

(a) ${(a,b), (a,c)}$. $quad$ (b) ${(a,a), (b,c)}$. $quad$ (c) *No solution:* every asymmetric relation is antisymmetric (below). $quad$ (d) ${(a,b), (b,a), (a,c)}$.
+ Let $R$ be an asymmetric relation on $A$: $forall x, y in A thin (x R y -> y cancel(R) x)$ #j[definition of asymmetry].
  + $equiv forall x, y in A thin (x cancel(R) y or y cancel(R) x)$ #j[implication law].
  + $=> forall x, y in A thin ((x cancel(R) y or y cancel(R) x) or x = y)$ #j[generalization].
  + $equiv forall x, y in A thin (lnot(x R y and y R x) or x = y)$ #j[De Morgan's law].
  + $equiv forall x, y in A thin (x R y and y R x -> x = y)$ #j[implication law].
+ The final formula is the definition of antisymmetry, so $R$ is antisymmetric: asymmetry makes it vacuously true. #qed]

#trap[T5 Q1 · Disprove with one named counterexample][
On strings over ${s, u}$, $a R b <-> op("len")(a) <= op("len")(b)$ is *not* a partial order: $s R u$ and $u R s$ but $s != u$, so $R$ is not antisymmetric. One counterexample suffices; there is no need to check reflexivity or transitivity.]

// ============================================================================
== Part VII · Definition locator for the original notes
// ============================================================================

#set text(size: 9.3pt)
#columns(2, gutter: 14pt)[
#let e(term, body, where) = block(below: 0.42em)[*#term:* #body #text(fill: muted)[§#where]]
#e[Absolute value][$|x| = x$ if $x >= 0$, $-x$ if $x < 0$.][10]
#e[Argument; valid; sound, unsound][premises then conclusion; valid if true premises force a true conclusion; sound if valid with true premises, else unsound.][4]
#e[Colorful][$n = 3k$ for some $k in ZZ$ (lecture only).][10]
#e[Conditional][$p -> q$, false only for T $->$ F; hypothesis $p$, conclusion $q$.][3]
#e[Critical row][truth-table row with all premises true.][4]
#e[Directed graph][one vertex per element; arrow $x -> y$ iff $x R y$.][19]
#e[Disjoint; mutually disjoint][$A inter B = nothing$; $A_i inter A_j = nothing$ for $i != j$.][16]
#e[Empty set; singleton][$nothing$, no elements; exactly one element.][14]
#e[Interval notation][$(a, b)$, $[a, b]$, $(a, b]$, $[a, b)$, $[a, oo)$, … as subsets of $RR$.][13]
#e[Lowest terms][$a slash b$ where 1 is the largest common divisor.][10]
#e[$n$-ary relation][subset of $A_1 times dots.c times A_n$.][19]
#colbreak()
#e[Negation, conjunction, disjunction][$lnot p$; $p and q$; $p or q$.][1]
#e[Ordered pair; $n$-tuple][equal iff equal componentwise.][15]
#e[Partition; component][non-empty subsets; each element in exactly one; its elements.][18]
#e[Predicate; domain; truth set][sentence with variables; allowed values; ${x in D : P(x)}$.][5]
#e[Rational / irrational][$r = a slash b$ with $a, b in ZZ$, $b != 0$ / not rational.][10]
#e[Reflexive / symmetric closure][$R union {(x, x) : x in A}$ / $R union R^(-1)$.][22]
#e[Relation; relation on $A$][subset of $A times B$; subset of $A times A$.][19]
#e[Representative][any member $b$ of $[a]$; then $[b] = [a]$.][23]
#e[Set equality][$A subset.eq B$ and $B subset.eq A$.][14]
#e[Set-roster notation][elements listed in braces.][13]
#e[Subset; superset][$forall x (x in A -> x in B)$; $B supset.eq A$.][14]
#e[Syllogism][two premises and a conclusion.][4]
#e[Uniqueness $exists!$][exactly one element satisfies it.][5]
#e[Universal conditional; universal existential; existential universal][$forall x (P -> Q)$; $forall exists$; $exists forall$.][5]
#e[Universal set][$U$, all objects under discussion.][16]
#e[Valid argument form][true premises force a true conclusion.][4, §8]
#e[Well-defined operation][binary operation on $A$ inducing a rule on classes independent of representatives.][23]
#e[Well-ordered][total order in which every non-empty subset has a smallest element.][24]
]

// ============================================================================
#pagebreak()
#set text(size: 10.3pt)
= Part VIII · Appendix A and Lecture Theorems (§33–34)
// ============================================================================

#lecture-reference(thm, kbox, lnot, PP, dv, simq, pleq)
